import { config } from "./config";

/**
 * Tous les endpoints data passent par le **BFF** (`/api/**`) ; seul l'échange OIDC est
 * adressé directement à l'issuer `quizup-identity`.
 */
export const ENDPOINTS = {
  auth: {
    loginCodes: `${config.oidcAuthority}/api/auth/login-codes`,
    sessions: `${config.oidcAuthority}/api/auth/sessions`,
    currentSession: `${config.oidcAuthority}/api/auth/sessions/current`,
  },
  me: "/api/me",
  suggestions: "/api/suggestions",
  clock: "/api/clock",
  home: "/api/home",
  topics: {
    list: "/api/topics",
    facets: "/api/topics/facets",
    categories: "/api/topic-categories",
    overview: (topicId: string) => `/api/topics/${topicId}/overview`,
    follow: (topicId: string) => `/api/topics/${topicId}/follow`,
    leaderboard: (topicId: string) => `/api/topics/${topicId}/leaderboard`,
    create: "/api/topics",
    name: (topicId: string) => `/api/topics/${topicId}/name`,
    description: (topicId: string) => `/api/topics/${topicId}/description`,
    category: (topicId: string) => `/api/topics/${topicId}/category`,
    emoji: (topicId: string) => `/api/topics/${topicId}/emoji`,
    color: (topicId: string) => `/api/topics/${topicId}/color`,
    imageUrl: (topicId: string) => `/api/topics/${topicId}/image-url`,
    publish: (topicId: string) => `/api/topics/${topicId}/publish`,
    questions: (topicId: string) => `/api/topics/${topicId}/questions`,
  },
  questions: {
    translations: (questionId: string) => `/api/questions/${questionId}/translations`,
    text: (questionId: string) => `/api/questions/${questionId}/text`,
    answers: (questionId: string) => `/api/questions/${questionId}/answers`,
    correctAnswer: (questionId: string) =>
      `/api/questions/${questionId}/correct-answer`,
    imageUrl: (questionId: string) => `/api/questions/${questionId}/image-url`,
    approve: (questionId: string) => `/api/questions/${questionId}/approve`,
    reject: (questionId: string) => `/api/questions/${questionId}/reject`,
  },
  profiles: {
    detail: (userId: string) => `/api/profiles/${userId}`,
    pseudonym: (userId: string) => `/api/profiles/${userId}/pseudonym`,
    bio: (userId: string) => `/api/profiles/${userId}/bio`,
    country: (userId: string) => `/api/profiles/${userId}/country`,
    avatarOptions: (userId: string) => `/api/profiles/${userId}/avatar-options`,
    language: (userId: string) => `/api/profiles/${userId}/language`,
    following: (userId: string) => `/api/profiles/${userId}/following`,
    followers: (userId: string) => `/api/profiles/${userId}/followers`,
    follow: (userId: string) => `/api/profiles/${userId}/follow`,
    games: (userId: string) => `/api/profiles/${userId}/games`,
    headToHead: (userId: string) => `/api/profiles/${userId}/head-to-head`,
    activity: (userId: string) => `/api/profiles/${userId}/activity`,
  },
  presence: {
    detail: (userId: string) => `/api/presence/${userId}`,
  },
  challenges: {
    create: "/api/challenges",
    mine: "/api/challenges/mine",
    detail: (challengeId: string) => `/api/challenges/${challengeId}`,
    accept: (challengeId: string) => `/api/challenges/${challengeId}/accept`,
    decline: (challengeId: string) => `/api/challenges/${challengeId}/decline`,
    cancel: (challengeId: string) => `/api/challenges/${challengeId}/cancel`,
  },
  lobbies: {
    create: "/api/lobbies",
    mine: "/api/lobbies/mine",
    detail: (lobbyId: string) => `/api/lobbies/${lobbyId}`,
    join: (lobbyId: string) => `/api/lobbies/${lobbyId}/join`,
    enter: (lobbyId: string) => `/api/lobbies/${lobbyId}/enter`,
    leave: (lobbyId: string) => `/api/lobbies/${lobbyId}/leave`,
    cancel: (lobbyId: string) => `/api/lobbies/${lobbyId}/cancel`,
    decline: (lobbyId: string) => `/api/lobbies/${lobbyId}/decline`,
    notifications: (lobbyId: string) => `/api/lobbies/${lobbyId}/notifications`,
  },
  notifications: {
    list: "/api/notifications",
    unreadCount: "/api/notifications/unread-count",
    read: (notificationId: string) => `/api/notifications/${notificationId}/read`,
    remove: (notificationId: string) => `/api/notifications/${notificationId}`,
    removeAll: "/api/notifications",
    readAll: "/api/notifications/read-all",
    preferences: "/api/notification-preferences",
    preference: (category: string) => `/api/notification-preferences/${category}`,
  },
  push: {
    vapidPublicKey: "/api/push/vapid-public-key",
    subscriptions: "/api/push/subscriptions",
  },
  matchmaking: {
    tickets: "/api/matchmaking/tickets",
    ticket: (ticketId: string) => `/api/matchmaking/tickets/${ticketId}`,
    cancel: (ticketId: string) => `/api/matchmaking/tickets/${ticketId}/cancel`,
    notifications: (ticketId: string) =>
      `/api/matchmaking/tickets/${ticketId}/notifications`,
  },
  games: {
    create: "/api/games",
    current: "/api/games/current",
    notifications: (gameId: string) => `/api/games/${gameId}/notifications`,
    result: (gameId: string) => `/api/games/${gameId}/result`,
    join: (gameId: string) => `/api/games/${gameId}/join`,
    leave: (gameId: string) => `/api/games/${gameId}/leave`,
    answer: (gameId: string) => `/api/games/${gameId}/answer`,
    abandon: (gameId: string) => `/api/games/${gameId}/abandon`,
    cancel: (gameId: string) => `/api/games/${gameId}/cancel`,
    rematch: (gameId: string) => `/api/games/${gameId}/rematch`,
    rematchAccept: (gameId: string) => `/api/games/${gameId}/rematch/accept`,
    rematchDecline: (gameId: string) => `/api/games/${gameId}/rematch/decline`,
    rematchCancel: (gameId: string) => `/api/games/${gameId}/rematch/cancel`,
  },
} as const;
